name: superstore_project
version: 1.0
config-version: 2
profile: postgres_profile

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  superstore_project:
    stg:
      +schema: staging
      +materialized: view

    marts:
      +schema: analytics
      +materialized: table

