name: superstore_project
version: 1.0
profile: postgres_profile
config-version: 2

# Define model paths and materialization strategies
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  marts:
    +materialized: table
  staging:
    +materialized: view

