version: 2

models:

  # ---------------------------------------------------------------------------
  # STAGING MODELS
  # ---------------------------------------------------------------------------

  - name: stg_orders
    description: >
      Cleaned and standardized order line data derived from the raw orders source.
      This model represents the atomic grain of the dataset, where each row
      corresponds to a single product within an order.
    columns:
      - name: row_id
        description: Unique identifier for each order line.
        tests:
          - unique
          - not_null

      - name: order_id
        description: Identifier for the customer order. Not unique, as one order
          may contain multiple product lines.
        tests:
          - not_null

      - name: order_date
        description: Date on which the order was placed.

      - name: ship_date
        description: Date on which the order was shipped.

      - name: customer_name
        description: Name of the customer who placed the order.

      - name: customer_segment
        description: Customer segment classification (e.g. Consumer, Corporate).

      - name: region
        description: Sales region associated with the order.
        tests:
          - not_null

      - name: product_name
        description: Name of the product sold.

      - name: product_category
        description: High-level product category.

      - name: product_subcategory
        description: Subcategory within the product category.

      - name: order_quantity
        description: Quantity of the product ordered.

      - name: sales
        description: Revenue generated by the order line.

      - name: profit
        description: Profit generated by the order line.

      - name: discount
        description: Discount applied to the order line.

      - name: product_base_margin
        description: Base margin associated with the product.

  - name: stg_returns
    description: >
      Cleaned return status data indicating whether an order was returned.
      Used to enrich order data with return information.
    columns:
      - name: order_id
        description: Identifier of the order associated with a return.
        tests:
          - not_null

      - name: status
        description: Indicates whether the order was returned.
        tests:
          - accepted_values:
              values: ['Returned', 'Not Returned']

  - name: stg_users
    description: >
      Lookup table mapping sales regions to their respective regional managers.
    columns:
      - name: region
        description: Sales region.
        tests:
          - not_null

      - name: manager
        description: Name of the regional manager responsible for the region.

  # ---------------------------------------------------------------------------
  # FACT MODEL
  # ---------------------------------------------------------------------------

  - name: final_orders_with_returns
    description: >
      Core fact table combining order-level data with return status and
      regional manager information.
      This model serves as the foundation for downstream analytical marts
      and is consumed directly by BI tools.
    columns:
      - name: order_id
        description: Identifier for the customer order.
        tests:
          - not_null

      - name: return_status
        description: Indicates whether the order was returned.

      - name: region_manager
        description: Regional manager responsible for the order.

      - name: sales
        description: Revenue generated by the order line.

      - name: profit
        description: Profit generated by the order line.

  # ---------------------------------------------------------------------------
  # MART MODELS
  # ---------------------------------------------------------------------------

  - name: mart_orders_summary_by_region
    description: >
      Executive-level regional performance summary aggregating sales,
      profit, discount behavior, and return rates by region and
      regional manager.
    columns:
      - name: region
        description: Sales region.

      - name: region_manager
        description: Manager responsible for the region.

      - name: total_orders
        description: Total number of distinct orders in the region.

      - name: returned_orders
        description: Number of distinct orders that were returned.

      - name: return_rate_percent
        description: Percentage of orders that were returned.

      - name: total_sales
        description: Total sales revenue for the region.

      - name: total_profit
        description: Total profit for the region.

      - name: avg_discount
        description: Average discount applied to orders in the region.

  - name: monthly_returns_trend
    description: >
      Monthly time-series model tracking return volume and return rate.
      Used to analyze trends, seasonality, and operational quality over time.
    columns:
      - name: month
        description: Month in which orders were placed.

      - name: returned_orders
        description: Number of returned orders in the month.

      - name: total_orders
        description: Total number of orders in the month.

      - name: return_rate
        description: Ratio of returned orders to total orders for the month.

  - name: product_performance
    description: >
      Product-level performance metrics including sales, profit,
      quantity sold, and average margin.
      Used by product and operations teams to assess product success.
    columns:
      - name: product_name
        description: Name of the product.

      - name: product_category
        description: Product category.

      - name: product_subcategory
        description: Product subcategory.

      - name: total_quantity_sold
        description: Total quantity sold across all orders.

      - name: total_sales
        description: Total sales revenue generated by the product.

      - name: total_profit
        description: Total profit generated by the product.

      - name: avg_margin
        description: Average base margin for the product.

      - name: num_orders
        description: Number of distinct orders containing the product.

  - name: top_customers
    description: >
      Customer-level aggregation identifying the highest-value customers
      based on total sales, order frequency, and average profit.
      Used for executive reporting and customer segmentation analysis.
    columns:
      - name: customer_name
        description: Name of the customer.

      - name: customer_segment
        description: Segment classification of the customer.

      - name: region
        description: Sales region of the customer.

      - name: total_sales
        description: Total sales revenue generated by the customer.

      - name: num_orders
        description: Number of distinct orders placed by the customer.

      - name: avg_profit
        description: Average profit per order for the customer.
